### GET Messages
GET http://localhost:3000/api/getMessages

### GET Single Message
GET http://localhost:3000/api/messages/2


### POST New User
POST http://localhost:3000/api/createUser
Content-Type: application/json; charset=utf-8

{
    "username": "Stefan2",
    "password": "Hockey123!"
}

### POST New Message
POST http://localhost:3000/api/createMessage
Content-Type: application/json; charset=utf-8

{
    "message": "jag bryr mig inte om hockey",
    "userId": 1
}

